# Generated by Django 4.0.3 on 2022-04-08 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=256)),
                ('course_name', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=256)),
                ('exam_content', models.TextField()),
                ('num_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('graded', models.BooleanField(default=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=256, unique=True)),
                ('hashed_password', models.CharField(max_length=1024)),
                ('salt', models.CharField(max_length=1024)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_on_Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_marks', models.DecimalField(decimal_places=5, max_digits=10)),
                ('is_practice', models.BooleanField(default=False)),
                ('date_user_finished', models.DateTimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_backend_django.exams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_backend_django.users')),
            ],
        ),
    ]
